project:
  type: website
  output-dir: docs

website:
  title: "Kiki Shimomae"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Digital Marketing Projects
      - href: marketinganalytics.qmd
        text: Marketing Analytics
      - href: resume.qmd
        text: Resume
      - href: coursework.qmd
        text: Coursework
format:
  html:
   theme:
    - cosmo
      - brand
css: styles.css
toc: true 
 
editor: visual
execute: 
  freeze: auto
